"""Add feedback table for LLM/user-submitted feature requests and bug reports.

Structured feedback capture surfaced through MCP tools:
- blender_submit_feedback (any bus user)
- blender_get_feedback / blender_list_feedback (transparent read for all users)

Reply flow is admin-only via scripts/reply_to_feedback.py in v1 (no MCP
tool to append replies). Shortcodes are ``{category-prefix}-{token}``,
e.g. ``fr-Kf3nQp7Xy_A``, generated by ``models.new_feedback_id``.

Revision ID: 20260916_0003
Revises: 20260528_0002
Create Date: 2026-09-16
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = "20260916_0003"
down_revision: Union[str, None] = "20260528_0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "feedback",
        sa.Column("id", sa.String(20), primary_key=True),
        sa.Column("submitter_user_id", sa.String(128), nullable=False),
        sa.Column("submitter_client_uuid", sa.String(128), nullable=True),
        sa.Column("submitter_client_label", sa.String(255), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "feature-request",
                "bug",
                "friction",
                "other",
                name="feedback_category",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "context",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in-progress",
                "resolved",
                "duplicate",
                "wontfix",
                name="feedback_status",
            ),
            nullable=False,
            server_default="open",
        ),
        sa.Column(
            "replies",
            JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index(
        "ix_feedback_submitter_user_id",
        "feedback",
        ["submitter_user_id"],
    )
    op.create_index(
        "ix_feedback_category",
        "feedback",
        ["category"],
    )
    op.create_index(
        "ix_feedback_status",
        "feedback",
        ["status"],
    )


def downgrade() -> None:
    op.drop_index("ix_feedback_status", table_name="feedback")
    op.drop_index("ix_feedback_category", table_name="feedback")
    op.drop_index("ix_feedback_submitter_user_id", table_name="feedback")
    op.drop_table("feedback")
    # Enums are separately-owned Postgres types; must be dropped
    # explicitly after all consumers are gone (drop_table alone leaves
    # the enum type sitting orphaned in pg_type).
    op.execute("DROP TYPE feedback_status")
    op.execute("DROP TYPE feedback_category")
